// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg3XTxVXngi_IiZfOggl7WHqAQAaNJBHI',
    appId: '1:936582001674:android:575202916d784775e45bf3',
    messagingSenderId: '936582001674',
    projectId: 'doctor-appointment-booki-fc9d6',
    storageBucket: 'doctor-appointment-booki-fc9d6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm9oZDouDcy-B5KZKjvbjQS_Ym_WjYLcU',
    appId: '1:936582001674:ios:447228bf15c1a7a1e45bf3',
    messagingSenderId: '936582001674',
    projectId: 'doctor-appointment-booki-fc9d6',
    storageBucket: 'doctor-appointment-booki-fc9d6.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentBookingApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7aOZuqIwqE3tCBeV9k7kz-nHyqS_HdgM',
    appId: '1:936582001674:web:3941db61545caed6e45bf3',
    messagingSenderId: '936582001674',
    projectId: 'doctor-appointment-booki-fc9d6',
    authDomain: 'doctor-appointment-booki-fc9d6.firebaseapp.com',
    storageBucket: 'doctor-appointment-booki-fc9d6.firebasestorage.app',
    measurementId: 'G-XXMYQGSY70',
  );
}
